# NumPy
NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. 

In [1]:
import numpy as np

 Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
my_list1=[4,6,9]
my_list1

[4, 6, 9]

In [4]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [5]:
np.array(my_list1)

array([4, 6, 9])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_matrix1=[[9,8,7,6,5],[4,3,2,1]]
my_matrix1

[[9, 8, 7, 6, 5], [4, 3, 2, 1]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods
There are lots of built-in ways to generate Arrays

# arange
Return evenly spaced values within a given interval.

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# zeros and ones
Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace¶
Return evenly spaced numbers over a specified interval.

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
np.linspace(1,5) #by default 50 values

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [25]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

# eye
Creates an identity matrix

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random
Numpy also has lots of ways to create random number arrays:

# rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [28]:
np.random.rand(3)

array([0.79062849, 0.08412961, 0.75542924])

In [29]:
np.random.rand(5,5)

array([[0.56836481, 0.76522591, 0.67978351, 0.72691851, 0.04526973],
       [0.57622445, 0.52322815, 0.33082043, 0.7360066 , 0.16651616],
       [0.20218555, 0.65013642, 0.49305898, 0.59778387, 0.91125383],
       [0.26325736, 0.58771723, 0.51387008, 0.83919204, 0.52526685],
       [0.37226667, 0.61251733, 0.83024656, 0.74806977, 0.64042658]])

In [30]:
np.random.rand(3,5)

array([[0.11407661, 0.17016898, 0.50462061, 0.21585202, 0.96454695],
       [0.5874283 , 0.27362303, 0.78484548, 0.31805768, 0.14131812],
       [0.88413566, 0.68555472, 0.82415963, 0.7326278 , 0.66125328]])

# randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [31]:
np.random.randn(2)

array([-0.90915337,  0.28484224])

In [32]:
np.random.randn(3)

array([ 0.67384963, -0.68485964, -2.54938856])

In [33]:
np.random.randn(5,5)

array([[ 0.78501482, -0.35481462, -0.85962453, -0.08646317,  1.78789267],
       [-0.54800627,  0.09464412, -0.44904017,  0.85580612,  1.17417619],
       [ 1.25634698,  0.52320817,  0.34806993,  0.6547909 , -0.07304378],
       [ 0.62814126,  0.64775268, -0.40352815,  0.02024833, -1.04587835],
       [ 0.06730445, -0.61600056, -0.79262061, -1.05715122, -2.45887159]])

In [34]:
np.random.randn(3,5)

array([[-1.46651057, -0.37946565, -2.0558485 ,  0.62577213, -0.97051732],
       [-0.69100375, -1.1458678 , -0.93227832,  0.70690822,  1.03286265],
       [-0.00880353,  0.59769049, -1.26708961,  1.2826459 ,  0.00882052]])

# randint
Return random integers from low (inclusive) to high (exclusive).

In [35]:
np.random.randint(1,100)

26

In [36]:
np.random.randint(1,50)

14

In [37]:
np.random.randint(1,100,10)

array([73, 29, 88, 73, 37, 12, 23, 76, 93, 66])

# Array Attributes and Methods
Let's discuss some useful attributes and methods or an array:

In [38]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr

array([19, 15,  3, 23, 33,  9, 14, 47, 32, 28])

In [41]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
rarr1=np.random.randint(0,7,10)
rarr1

array([2, 6, 6, 1, 6, 2, 6, 0, 2, 2])

# Reshape
Returns an array containing the same data with a new shape.

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr1.shape

(10,)

In [45]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [46]:
ranarr

array([19, 15,  3, 23, 33,  9, 14, 47, 32, 28])

In [47]:
ranarr.max()

47

In [48]:
rarr1.max()

6

In [49]:
rarr1.min()

0

In [50]:
ranarr.argmax()

7

In [51]:
ranarr.min()

3

In [52]:
ranarr.argmin()

2

# Shape
Shape is an attribute that arrays have (not a method):

In [53]:
# Vector
arr.shape

(25,)

In [54]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [55]:
arr.reshape(1,25).shape

(1, 25)

In [56]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [57]:
arr.reshape(25,1).shape

(25, 1)

# dtype
You can also grab the data type of the object in the array:

In [58]:
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In [59]:
#Creating sample array
arr = np.arange(0,11)

In [60]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr1=np.random.randint(5,20,10)
arr1

array([15, 19, 15,  5, 13, 19, 19,  9,  7, 11])

In [62]:
arr1.max()

19

In [63]:
arr1.argmin()

3

# Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [64]:
arr1[8]

7

In [65]:
arr1[-1]

11

In [66]:
arr1[1:6]

array([19, 15,  5, 13, 19])

In [67]:
#Get a value at an index
arr[8]

8

In [68]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [69]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [70]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [71]:
arr1[1:4]=10
arr1

array([15, 10, 10, 10, 13, 19, 19,  9,  7, 11])

In [72]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [74]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [75]:
slice_of_arr1 = arr1[2:6]
slice_of_arr1[:]= 5
slice_of_arr1

array([5, 5, 5, 5])

In [76]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row,col].

In [78]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [80]:
arr_2d[0]

array([ 5, 10, 15])

In [81]:
arr_2d[1][2]

30

In [82]:
arr_2d[1,2]

30

In [83]:
arr_2d[2,2]

45

In [84]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [85]:
# Getting individual element value
arr_2d[1,0]

20

In [86]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [87]:
arr_2d[:2,0:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [88]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [89]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [90]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

# Fancy Indexing
Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [91]:
#Set up matrix
arr2d = np.zeros((10,10))

In [92]:
#Length of array
arr_length = arr2d.shape[1]

In [93]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

# Selection
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [97]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [99]:
bool_arr = arr>4

In [100]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [101]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [102]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

# Arithmetic

In [104]:
arr = np.arange(0,10)

In [105]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [106]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [107]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [108]:
arr1=np.arange(11,21)

In [109]:
arr1 + arr1

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [110]:
arr1*arr1

array([121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [111]:
arr1-arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
arr1/0

<ipython-input-112-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [113]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

<ipython-input-113-2f119c028196>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [114]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-114-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [115]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Universal Array Functions

In [116]:
#Taking Square Roots
np.sqrt(arr1)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [117]:
#Calcualting exponential (e^)
np.exp(arr1)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [118]:
np.max(arr)
np.max(arr1)
#same as arr.max()

20

In [119]:
np.sin(arr)
np.sin(arr1)

array([-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525])

In [120]:
np.log(arr)
np.log(arr1)

<ipython-input-120-e86497cda2f8>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

# NumPy Exercises

# Create an array of 10 zeros

In [121]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create an array of 10 ones

In [122]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Create an array of 10 fives

In [123]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Create an array of the integers from 10 to 50¶

In [124]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# Create a 3x3 matrix with values ranging from 0 to 8

In [125]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Create a 3x3 identity matrix

In [126]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Use NumPy to generate a random number between 0 and 1¶

In [127]:
np.random.rand(1)

array([0.44643228])

# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution¶

In [128]:
np.random.randn(25)

array([-2.1274244 , -0.73492022,  0.18032956, -0.04903405,  1.61987327,
        0.11653439,  0.67971185,  0.8893676 , -0.36836696,  0.7335173 ,
       -0.666476  ,  0.81740668, -1.2303326 ,  2.2474809 ,  0.53456166,
        0.04609189,  0.3669331 , -0.93444228,  1.67343602, -0.13106469,
        0.16308385, -0.74590356, -2.40466868, -1.26655602, -1.03979828])

In [130]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Create an array of 20 linearly spaced points between 0 and 1:¶

In [131]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [132]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [133]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [134]:
mat[3,4]

20

In [135]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [136]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [137]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Get the sum of all the values in mat

In [138]:
mat.sum()

325

# Get the standard deviation of the values in mat

In [139]:
mat.std()

7.211102550927978

# Get the sum of all the columns in mat# Get the sum of all the columns in mat

In [140]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])